Add reset options argument to recurrent buffers
AlignmentResearch/learned-planners-stable-baselines3 pull request #28
Opened 2024-03-21 17:20 UTC by taufeeque9

This PR adds the `options` argument to the `reset` methods in the DummyVecEnv and the VecTransposeImage classes. These are required for indexing on levels during resetting in the PR: https://github.com/AlignmentResearch/gym-sokoban/pull/2.

2024-03-22 18:14 UTC, rhaps0dy requested changes
pls add types :)

2024-03-22 18:14 UTC, rhaps0dy commented on stable_baselines3/common/vec_env/dummy_vec_env.py
> +    def reset(self, options=None) -> VecEnvObs:
Should have a type, e.g. `Optional[Any]`, or more specific if possible

2024-03-22 18:16 UTC, rhaps0dy approved these changes
LGTM but please add types and fix the CI

2024-03-25 18:21 UTC, rhaps0dy commented on stable_baselines3/common/vec_env/subproc_vec_env.py
> +            remote.send(("reset", (self._seeds[env_idx], options)))
This may break RL environments that don't expect any options in the `reset`. Maybe only send a tuple if `options` is not None?

2024-03-25 22:56 UTC, taufeeque9 commented on stable_baselines3/common/vec_env/subproc_vec_env.py
> +            remote.send(("reset", (self._seeds[env_idx], options)))
Good suggestion! Doing this everywhere.

2024-03-26 03:36 UTC, taufeeque9 commented
This PR is no longer required. So I'll close it without merging.

2024-03-26 03:36 UTC, closed without merging